
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[328] =
    {   0,
        0,    0,    0,    0,   79,   77,   78,   51,   77,   51,
       51,   77,   50,   51,   51,   51,   42,   51,   51,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   51,   51,   75,   75,
       67,    0,   74,   43,    0,   68,    0,    0,   48,   52,
       71,    0,   45,    0,   42,   70,   57,   60,   55,   53,
       54,   56,   65,   66,   64,   61,   62,   41,   41,   41,
       41,   10,   41,   41,   16,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   36,   41,
       41,   41,   41,   72,    0,    0,    0,   69,   76,    0,

       73,   44,    0,    0,   47,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   45,    0,    0,   63,
       59,   58,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   22,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   34,
       41,   41,   41,   41,   41,   41,    0,   49,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   45,    0,   41,   41,    4,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   25,   41,   41,   28,   29,   30,   41,
       41,   33,   41,   37,   41,   41,   41,   41,    0,    0,
        0,    0,    0,    0,    0,   45,    0,    2,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   24,   26,   41,   41,   41,
       41,   41,   38,   39,   41,    0,    0,    0,    0,   46,
       41,    5,   41,   41,   41,   41,   41,   41,   41,   41,
       15,   17,   41,   41,   41,   41,   41,   41,   41,   41,
       35,    1,   41,   46,    0,   41,   41,   41,   41,   41,
       11,   41,   13,   41,   41,   41,   41,   21,   23,   41,

       41,   41,   41,   46,    3,    6,    7,   41,   41,   12,
       14,   41,   19,   41,   27,   41,   32,   41,   41,    9,
       41,   20,   31,   40,    8,   18,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    4,    1,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   36,   48,   49,   50,
       51,   52,   53,   54,   36,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   64,   36,   65,   66,   67,
       68,   69,   70,   71,   72,   73,   74,   75,   36,   76,
       77,   78,   79,   80,   81,   82,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[83] =
    {   0,
        1,    2,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[340] =
    {   0,
        0,    0,  538,  528,  540,  888,  888,  503,   79,  888,
      488,   80,  888,  478,  463,   82,   88,  443,  103,   46,
        0,   84,   60,   98,   57,   67,   68,   77,   89,   76,
      104,   99,  122,  127,   93,  108,  438,  151,  888,  430,
      888,  401,  888,  162,    0,  888,   81,  230,  888,  888,
      888,  151,  170,  177,  185,  888,  888,  888,  344,  888,
      328,  888,  334,  888,  888,  888,  888,    0,   93,  178,
      106,  167,  161,  178,  181,  176,  183,  205,  158,  222,
      176,  182,  187,  181,  187,  219,  229,  228,  228,  230,
      229,  237,  231,  888,  276,  350,  284,  300,  888,  274,

      888,  250,  131,  424,  888,  147,  215,  302,  306,  274,
      304,  200,  310,  321,  322,  323,  315,    0,  259,  888,
      888,  888,  257,  291,  310,  308,  314,  311,  276,  314,
      317,  316,  327,  308,  318,  325,  328,    0,  334,  343,
      352,  342,  355,  372,  373,  374,  357,  369,  367,    0,
      362,  368,  383,  371,  375,  382,  333,  429,  433,  443,
      458,  449,  450,  321,  462,  466,  468,  474,  442,  486,
      494,  478,  501,  401,  510,  511,  512,  517,  518,  527,
      551,  476,  427,  443,  479,    0,  461,  499,  486,  488,
      503,  519,  520,  513,  524,  520,  523,  519,  525,  531,

      543,  540,  541,    0,  549,  541,    0,    0,    0,  560,
      551,    0,  563,    0,  556,  552,  558,  572,  535,  615,
      692,  545,  622,  766,  609,  598,  631,    0,  575,  610,
      596,  604,  611,  606,  606,  605,  608,  627,  616,  628,
      631,  630,  633,  620,  624,    0,    0,  627,  634,  646,
      632,  636,    0,    0,  650,  663,  678,  696,  720,  709,
      659,    0,  656,  660,  677,  671,  691,  702,  708,  701,
        0,    0,  695,  696,  708,  706,  714,  731,  719,  724,
        0,    0,  733,  738,    0,  749,  734,  738,  734,  754,
        0,  744,    0,  749,  745,  773,  761,    0,    0,  758,

      769,  782,  780,    0,    0,    0,    0,  781,  770,    0,
        0,  771,    0,  777,    0,  778,    0,  776,  783,    0,
      805,    0,    0,    0,    0,    0,  888,  860,  865,  867,
      872,  877,  224,  882,  204,  188,  168,  153,  146
    } ;

static const flex_int16_t yy_def[340] =
    {   0,
      327,    1,  328,  328,  327,  327,  327,  327,  327,  327,
      327,  329,  327,  327,  327,  327,  327,  327,  327,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  327,  331,  327,  327,
      327,  332,  327,  327,  333,  327,  334,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  327,  331,  327,  331,  331,  327,  332,

      327,  333,  334,  327,  327,  334,  334,  334,  334,  334,
      334,  335,  334,  334,  334,  334,  327,  336,  327,  327,
      327,  327,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  331,  331,  331,  331,
      331,  331,  331,  337,  331,  331,  331,  331,  334,  334,
      334,  334,  334,  338,  334,  334,  334,  334,  334,  334,
      334,  336,  327,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  331,  331,
      331,  334,  334,  181,  334,  336,  327,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  331,  334,  327,  327,  327,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  327,  339,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  339,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,    0,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327
    } ;

static const flex_int16_t yy_nxt[971] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   13,   14,
       10,   13,   15,   16,   10,   17,   17,   17,   17,   13,
       13,   18,   19,   10,   10,   20,   21,   22,   23,   24,
       25,   21,   26,   21,   21,   21,   27,   28,   29,   30,
       31,   21,   32,   33,   34,   35,   36,   21,   21,   21,
       10,   10,   10,   37,   20,   21,   22,   23,   24,   25,
       21,   26,   21,   21,   27,   28,   29,   30,   31,   21,
       32,   33,   34,   35,   36,   21,   21,   21,   13,   38,
       13,   10,   42,   48,  104,   52,   49,  105,   69,   72,
       78,   43,   80,   81,   44,   44,   44,   53,   53,   53,

       53,   54,   79,   55,   55,   55,   55,   57,   58,   70,
       82,   45,   59,   60,   83,   61,   69,   62,   72,   78,
       84,   80,   81,   71,   63,   64,   65,   66,   87,   85,
       79,   92,   73,   93,  104,  123,   74,   49,   70,   82,
       45,   75,   76,   83,  127,   77,   86,   88,   84,  304,
      104,   71,   90,   49,   96,   89,  103,   87,   85,   92,
       91,   73,   93,  123,   74,   97,  117,  117,  117,   75,
       76,   95,  127,   77,   86,   54,   88,   44,   44,   44,
       52,   90,   67,  118,   89,   53,   53,   53,   53,   91,
      130,  182,   53,   53,   53,   53,  139,  128,   54,  119,

       55,   55,   55,   55,  124,  131,  125,   47,  133,  135,
      136,  143,  118,  129,  142,  144,  181,  181,  104,  130,
      126,  105,  132,  145,  139,  134,  128,  102,  119,  146,
       98,  106,  137,  124,  131,  125,  107,  133,  135,  136,
      143,  129,  142,  138,  144,  108,  109,  108,  126,  140,
      132,  145,  147,  134,  149,  107,  110,  146,  148,  150,
      111,  137,  112,   54,  151,  141,  152,  153,  113,  154,
      155,  138,  114,  156,  115,  101,  116,  104,  140,   96,
      105,  147,  184,  149,  107,  110,  148,   96,  150,  111,
      157,  112,  151,  141,  152,  153,  113,  154,  157,  155,

      114,  156,  115,   96,  116,  104,  183,  104,  105,  104,
      105,  184,  105,  104,  157,  193,  105,  179,  179,  179,
      185,  180,  180,  180,  104,  104,  104,  105,  105,  105,
      117,  117,  117,  188,  183,  186,   96,  221,  221,  187,
      192,  194,  195,  193,  119,  196,  122,  157,  189,  185,
      198,  121,  197,  120,  200,  158,  159,  190,  191,  199,
      201,  202,  188,  158,  186,  160,  161,  160,  187,  192,
      194,  195,  203,  119,  196,  159,  162,  189,  198,  158,
      163,  197,  164,  200,  204,  190,  191,  199,  165,  201,
      202,  205,  166,  206,  167,  210,  168,  207,  208,  209,

      211,  203,  101,  212,  159,  162,  213,  214,  215,  163,
      216,  164,  158,  204,  217,  218,  165,  224,  224,  205,
      166,  206,  167,  210,  168,  106,  207,  208,  209,  211,
      169,  212,   96,   99,  213,  214,   96,  215,  216,  170,
      171,  170,  217,  157,  218,  104,   96,  157,   49,  169,
      172,   94,   96,   96,  173,   56,  174,  157,  219,  219,
      219,   96,  175,  157,  157,   96,  176,  227,  177,   96,
      178,   96,  157,  220,  220,  220,  157,   96,  169,  172,
      157,  104,  157,  173,   49,  174,   51,   50,  157,  104,
      175,  228,   49,   46,  176,  227,  177,  104,  178,  230,

       49,  222,  222,  222,  104,  226,  229,   49,  158,  223,
      223,  223,  158,  104,  104,  104,   49,   49,   49,  228,
      104,  104,  158,   49,  105,   41,  231,  230,  158,  158,
      104,  232,  233,  105,  226,  229,  234,  158,   96,  327,
       40,  158,  179,  179,  179,  158,  235,  158,  104,  157,
       40,   49,  327,  158,  104,  231,  236,  105,  237,  232,
      233,  238,  239,  240,  241,  234,  225,  225,  225,  225,
      242,  243,  244,  245,  247,  235,  225,  225,  225,  225,
      225,  225,  327,  246,  236,  248,  237,  249,  251,  238,
      239,  240,  241,  250,  252,  253,  254,  255,  242,  243,

      327,  244,  245,  247,  261,  225,  225,  225,  225,  225,
      225,  246,  104,  248,  158,  105,  249,  251,   96,  327,
      327,  250,  252,  253,  254,  104,  255,  226,   49,  157,
      219,  219,  219,  261,  258,  262,  265,  222,  222,  222,
      263,  259,  264,  259,  266,  183,  260,  260,  260,  260,
      267,  268,  269,  270,  327,  271,  226,  272,  273,  274,
      275,  327,  276,  277,  262,  265,   96,  279,  263,  278,
      264,  280,  266,  183,  281,  282,  283,  157,  267,  268,
      269,  104,  270,  271,   49,  287,  272,  273,  274,  275,
      276,  277,  327,  327,  158,   96,  279,  278,  327,  327,

      280,  286,  281,  282,  288,  283,  157,  256,  256,  256,
      256,  284,  284,  284,  287,  289,  290,  256,  256,  256,
      256,  256,  256,  258,  260,  260,  260,  260,  285,  286,
      291,  292,  288,  293,  294,  260,  260,  260,  260,  295,
      296,  297,  158,  289,  290,  298,  256,  256,  256,  256,
      256,  256,  299,  284,  284,  284,  300,  285,  291,  301,
      292,  302,  293,  294,  327,  327,  327,  295,  296,  303,
      297,  158,   49,  298,  305,  327,  306,  307,  308,  309,
      299,  257,  257,  257,  257,  300,  310,  301,  311,  302,
      312,  257,  257,  257,  257,  257,  257,  303,  313,  327,

      314,  315,  316,  305,  306,  307,  308,  317,  309,  318,
      319,  327,  320,  321,  310,  322,  311,  323,  312,  324,
      257,  257,  257,  257,  257,  257,  325,  313,  314,  315,
      326,  316,  327,  327,  327,  327,  317,  327,  318,  319,
      320,  321,  327,  322,  327,  323,  327,  324,  327,  327,
      327,  327,  327,  327,  325,  327,  327,  327,  327,  326,
       39,   39,   39,   39,   39,   47,  327,   47,   47,   47,
       68,   68,   95,  327,  327,   95,   95,  100,  100,  100,
      100,  100,  103,  327,  103,  103,  103,    5,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327
    } ;

static const flex_int16_t yy_chk[971] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    9,   12,   47,   16,   12,   47,   20,   23,
       25,    9,   26,   27,    9,    9,    9,   16,   16,   16,

       16,   17,   25,   17,   17,   17,   17,   19,   19,   22,
       28,    9,   19,   19,   29,   19,   20,   19,   23,   25,
       30,   26,   27,   22,   19,   19,   19,   19,   32,   31,
       25,   35,   24,   36,  103,   69,   24,  103,   22,   28,
        9,   24,   24,   29,   71,   24,   31,   33,   30,  339,
      106,   22,   34,  106,   38,   33,  338,   32,   31,   35,
       34,   24,   36,   69,   24,   38,   52,   52,   52,   24,
       24,  337,   71,   24,   31,   44,   33,   44,   44,   44,
       54,   34,   19,   52,   33,   53,   53,   53,   53,   34,
       73,  336,   54,   54,   54,   54,   79,   72,   55,   53,

       55,   55,   55,   55,   70,   74,   70,  335,   75,   76,
       77,   82,   52,   72,   81,   83,  112,  112,  107,   73,
       70,  107,   74,   84,   79,   75,   72,  333,   53,   85,
       38,   48,   78,   70,   74,   70,   48,   75,   76,   77,
       82,   72,   81,   78,   83,   48,   48,   48,   70,   80,
       74,   84,   86,   75,   87,   48,   48,   85,   86,   87,
       48,   78,   48,  102,   88,   80,   89,   90,   48,   91,
       92,   78,   48,   93,   48,  100,   48,  110,   80,   95,
      110,   86,  123,   87,   48,   48,   86,   97,   87,   48,
       95,   48,   88,   80,   89,   90,   48,   91,   97,   92,

       48,   93,   48,   98,   48,  108,  119,  111,  108,  109,
      111,  123,  109,  113,   98,  129,  113,  108,  108,  108,
      124,  109,  109,  109,  114,  115,  116,  114,  115,  116,
      117,  117,  117,  126,  119,  125,  157,  164,  164,  125,
      128,  130,  131,  129,  117,  132,   63,  157,  127,  124,
      134,   61,  133,   59,  136,   95,   96,  127,  127,  135,
      137,  139,  126,   97,  125,   96,   96,   96,  125,  128,
      130,  131,  140,  117,  132,   96,   96,  127,  134,   98,
       96,  133,   96,  136,  141,  127,  127,  135,   96,  137,
      139,  142,   96,  143,   96,  147,   96,  144,  145,  146,

      148,  140,   42,  149,   96,   96,  151,  152,  153,   96,
      154,   96,  157,  141,  155,  156,   96,  174,  174,  142,
       96,  143,   96,  147,   96,  104,  144,  145,  146,  148,
      104,  149,  158,   40,  151,  152,  159,  153,  154,  104,
      104,  104,  155,  158,  156,  169,  160,  159,  169,  104,
      104,   37,  162,  163,  104,   18,  104,  160,  160,  160,
      160,  161,  104,  162,  163,  165,  104,  183,  104,  166,
      104,  167,  161,  161,  161,  161,  165,  168,  104,  104,
      166,  172,  167,  104,  172,  104,   15,   14,  168,  170,
      104,  184,  170,   11,  104,  183,  104,  171,  104,  187,

      171,  170,  170,  170,  173,  182,  185,  173,  158,  171,
      171,  171,  159,  175,  176,  177,  175,  176,  177,  184,
      178,  179,  160,  178,  179,    8,  188,  187,  162,  163,
      180,  189,  190,  180,  182,  185,  191,  161,  219,    5,
        4,  165,  180,  180,  180,  166,  192,  167,  222,  219,
        3,  222,    0,  168,  181,  188,  193,  181,  194,  189,
      190,  195,  196,  197,  198,  191,  181,  181,  181,  181,
      199,  200,  201,  202,  205,  192,  181,  181,  181,  181,
      181,  181,    0,  203,  193,  206,  194,  210,  213,  195,
      196,  197,  198,  211,  215,  216,  217,  218,  199,  200,

        0,  201,  202,  205,  229,  181,  181,  181,  181,  181,
      181,  203,  225,  206,  219,  225,  210,  213,  220,    0,
        0,  211,  215,  216,  217,  223,  218,  226,  223,  220,
      220,  220,  220,  229,  227,  230,  233,  223,  223,  223,
      231,  227,  232,  227,  234,  226,  227,  227,  227,  227,
      235,  236,  237,  238,    0,  239,  226,  240,  241,  242,
      243,    0,  244,  245,  230,  233,  256,  249,  231,  248,
      232,  250,  234,  226,  251,  252,  255,  256,  235,  236,
      237,  257,  238,  239,  257,  263,  240,  241,  242,  243,
      244,  245,    0,    0,  220,  221,  249,  248,    0,    0,

      250,  261,  251,  252,  264,  255,  221,  221,  221,  221,
      221,  258,  258,  258,  263,  265,  266,  221,  221,  221,
      221,  221,  221,  259,  260,  260,  260,  260,  258,  261,
      267,  268,  264,  269,  270,  259,  259,  259,  259,  273,
      274,  275,  256,  265,  266,  276,  221,  221,  221,  221,
      221,  221,  277,  284,  284,  284,  278,  258,  267,  279,
      268,  280,  269,  270,    0,    0,    0,  273,  274,  283,
      275,  221,  224,  276,  286,    0,  287,  288,  289,  290,
      277,  224,  224,  224,  224,  278,  292,  279,  294,  280,
      295,  224,  224,  224,  224,  224,  224,  283,  296,    0,

      297,  300,  301,  286,  287,  288,  289,  302,  290,  303,
      308,    0,  309,  312,  292,  314,  294,  316,  295,  318,
      224,  224,  224,  224,  224,  224,  319,  296,  297,  300,
      321,  301,    0,    0,    0,    0,  302,    0,  303,  308,
      309,  312,    0,  314,    0,  316,    0,  318,    0,    0,
        0,    0,    0,    0,  319,    0,    0,    0,    0,  321,
      328,  328,  328,  328,  328,  329,    0,  329,  329,  329,
      330,  330,  331,    0,    0,  331,  331,  332,  332,  332,
      332,  332,  334,    0,  334,  334,  334,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[79] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mini.l"
#line 2 "mini.l"
  #include <stdio.h>
  #include "tokens.h"
  #include "mini.tab.h"
#line 797 "lex.yy.c"

#line 799 "lex.yy.c"

#define INITIAL 0
#define COMENTARIO 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 25 "mini.l"

#line 1019 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 328 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 888 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "mini.l"
{printf("linea %d, - - - - -  Tamaño: %s\n", yylineno, yytext); return(TAMANO);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ARRAY);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CABECERA);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CADA);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CADENA);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CARACTER);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CONJUNTO);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CONSTANTES);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CONTINUAR);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(DE);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(DEFECTO);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(DEVOLVER);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(EJECUTA);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ENCAMBIO);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ENTERO);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ES);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ESCAPE);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ESTRUCTURA);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ETIQUETA);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 46 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(EXCEPCION);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 47 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(FICHERO);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(FIN);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(FUNCION);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 50 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(HACER);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(HASH);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(LANZA);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(MIENTRAS);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(NADA);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(OTRA);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(PARA);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(PRINCIPIO);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 58 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(PROGRAMA);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(REAL);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 60 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(REF);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(SALTAR);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 62 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(SI);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 63 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(SINO);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 64 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(TIPOS);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 65 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(UNION);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 66 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(VARIABLES);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "mini.l"
{printf("linea %d, identificador: %s\n", yylineno, yytext); return(IDENTIFICADOR);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "mini.l"
{printf("linea %d, decimal: %s\n", yylineno, yytext); return(CTC_ENTERA);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "mini.l"
{printf("linea %d, octal: %s\n", yylineno, yytext); return(CTC_ENTERA);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "mini.l"
{printf("linea %d, hexadecimal: %s\n", yylineno, yytext); return(CTC_ENTERA);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "mini.l"
{printf("linea %d, número real: %s\n", yylineno, yytext); return(CTC_REAL);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "mini.l"
{printf("linea %d, número real: %s\n", yylineno, yytext); return(CTC_REAL);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "mini.l"
{printf("linea %d, carácter: %s\n", yylineno, yytext); return(CTC_CARACTER);}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 75 "mini.l"
{printf("linea %d, cadena: %s\n", yylineno, yytext); return(CTC_CADENA);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "mini.l"
{printf("linea %d, ruta: %s\n", yylineno, yytext); return(RUTA);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "mini.l"
{printf("linea %d, delimitador: %s\n", yylineno, yytext); return(yytext[0]);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "mini.l"
{printf("linea %d, operador: %s\n", yylineno, yytext); return(yytext[0]);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 80 "mini.l"
{printf("linea %d, potencia: %s\n", yylineno, yytext); return(POTENCIA);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "mini.l"
{printf("linea %d, suma_asig: %s\n", yylineno, yytext); return(SUMA_ASIG);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 82 "mini.l"
{printf("linea %d, resta_asig: %s\n", yylineno, yytext); return(RESTA_ASIG);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "mini.l"
{printf("linea %d, multiplicar_asig: %s\n", yylineno, yytext); return(MULT_ASIG);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "mini.l"
{printf("linea %d, dividir_asig: %s\n", yylineno, yytext); return(DIV_ASIG);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 85 "mini.l"
{printf("linea %d, módulo_asig: %s\n", yylineno, yytext); return(MOD_ASIG);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 86 "mini.l"
{printf("linea %d, flechaIzq_asig: %s\n", yylineno, yytext); return(FI_ASIG);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 87 "mini.l"
{printf("linea %d, flechaDer_asig: %s\n", yylineno, yytext); return(FD_ASIG);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 88 "mini.l"
{printf("linea %d, AND_asig: %s\n", yylineno, yytext); return(AND_ASIG);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 89 "mini.l"
{printf("linea %d, XOR_asig: %s\n", yylineno, yytext); return(XOR_ASIG);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 90 "mini.l"
{printf("linea %d, OR_asig: %s\n", yylineno, yytext); return(OR_ASIG);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 91 "mini.l"
{printf("linea %d, potencia_asig: %s\n", yylineno, yytext); return(POT_ASIG);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 92 "mini.l"
{printf("linea %d, mayor_igual: %s\n", yylineno, yytext); return(GE);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 93 "mini.l"
{printf("linea %d, menor_igual: %s\n", yylineno, yytext); return(LE);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 94 "mini.l"
{printf("linea %d, igual: %s\n", yylineno, yytext); return(EQ);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 95 "mini.l"
{printf("linea %d, distinto: %s\n", yylineno, yytext); return(NEQ);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 96 "mini.l"
{printf("linea %d, AND: %s\n", yylineno, yytext); return(AND);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 97 "mini.l"
{printf("linea %d, OR: %s\n", yylineno, yytext); return(OR);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 98 "mini.l"
{printf("linea %d, flechaIzq: %s\n", yylineno, yytext); return(FLECHA_IZDA);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 99 "mini.l"
{printf("linea %d, flechaDer: %s\n", yylineno, yytext); return(FLECHA_DCHA);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 100 "mini.l"
{printf("linea %d, indirección: %s\n", yylineno, yytext); return(INDIRECCION);}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 103 "mini.l"
;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 104 "mini.l"
BEGIN(COMENTARIO);
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 105 "mini.l"
;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 106 "mini.l"
BEGIN(INITIAL);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 108 "mini.l"
printf("linea %d, error\n", yylineno);
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 111 "mini.l"
ECHO;
	YY_BREAK
#line 1479 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMENTARIO):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 328 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 328 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 327);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 111 "mini.l"



int yywrap() {
  return(1);
}

int main(int argc, char *argv[]) {
  if (argc < 2) {
    printf("Uso: ./mini NombreArchivo\n");
  } else {
    yyin = fopen(argv[1],"r");
    while (yylex());
  }
}
