
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[315] =
    {   0,
        0,    0,    0,    0,   80,   78,   77,   77,   51,   78,
       51,   51,   78,   50,   51,   51,   51,   42,   51,   51,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   51,   51,   75,
       75,   67,    0,   74,   43,    0,   68,    0,    0,   48,
       52,   71,    0,   45,    0,   42,   70,   57,   60,   55,
       53,   54,   56,   65,   66,   64,   61,   62,   41,   41,
       41,   41,   10,   41,   41,   16,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   36,
       41,   41,   41,   41,   72,    0,    0,   69,   76,    0,

       73,   44,    0,    0,   47,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   45,    0,    0,   63,
       59,   58,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   22,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   34,
       41,   41,   41,   41,   41,   41,    0,   49,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   45,    0,   41,   41,    4,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   25,   41,   41,   28,   29,   30,   41,

       41,   33,   41,   37,   41,   41,   41,   41,    0,    0,
        0,    0,    0,   45,    0,    2,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   24,   26,   41,   41,   41,   41,   41,
       38,   39,   41,    0,    0,    0,   46,   41,    5,   41,
       41,   41,   41,   41,   41,   41,   41,   15,   17,   41,
       41,   41,   41,   41,   41,   41,   41,   35,    1,   41,
       46,    0,   41,   41,   41,   41,   41,   11,   41,   13,
       41,   41,   41,   41,   21,   23,   41,   41,   41,   41,
       46,    3,    6,    7,   41,   41,   12,   14,   41,   19,

       41,   27,   41,   32,   41,   41,    9,   41,   20,   31,
       40,    8,   18,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   37,   49,   50,   51,
       52,   53,   54,   55,   37,    1,   56,   57,   58,   59,

       60,   61,   62,   63,   64,   65,   37,   66,   67,   68,
       69,   70,   71,   72,   73,   74,   75,   76,   37,   77,
       78,   79,   80,   81,   82,   83,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[84] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    4,    4,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        3,    1,    1
    } ;

static const flex_int16_t yy_base[327] =
    {   0,
        0,    0,  489,  457,  469,  784,  784,  784,  403,   79,
      784,  418,   80,  784,  412,  390,   82,   88,  397,  103,
       46,    0,   84,   60,   98,   57,   67,   68,   77,   89,
       76,  104,   99,  122,  127,   93,  108,  394,   70,  784,
      338,  784,  334,  784,  150,    0,  784,  131,  189,  784,
      784,  784,  162,  170,  193,  185,  784,  784,  784,  324,
      784,  259,  784,  218,  784,  784,  784,  784,    0,  102,
      190,  154,  167,  125,  180,  190,  160,  198,  202,  199,
      224,  200,  213,  221,  211,  214,  231,  247,  221,  231,
      237,  235,  243,  237,  784,  225,  259,  784,  784,  211,

      784,  178,  147,  338,  784,  165,  280,  293,  308,  284,
      285,  296,  286,  312,  313,  314,  311,    0,  247,  784,
      784,  784,  275,  292,  307,  305,  303,  302,  295,  315,
      318,  319,  324,  303,  310,  323,  324,    0,  330,  329,
      335,  334,  350,  364,  365,  366,  356,  364,  362,    0,
      356,  362,  377,  366,  367,  370,    0,  784,  411,  424,
      432,  439,  440,  420,  447,  448,  449,  453,  454,  455,
      470,  386,  422,  415,  437,    0,  428,  447,  432,  434,
      442,  452,  445,  437,  446,  442,  449,  447,  457,  467,
      484,  481,  474,    0,  493,  477,    0,    0,    0,  492,

      480,    0,  498,    0,  493,  489,  495,  509,  466,  462,
      550,  562,  533,  511,  590,    0,  512,  521,  510,  517,
      547,  519,  527,  530,  537,  548,  545,  565,  568,  567,
      570,  568,  572,    0,    0,  571,  565,  589,  580,  589,
        0,    0,  589,  626,  619,  630,  637,  588,    0,  602,
      593,  602,  597,  610,  628,  634,  628,    0,    0,  619,
      620,  633,  630,  633,  642,  632,  636,    0,    0,  638,
      666,    0,  650,  636,  640,  640,  651,    0,  643,    0,
      648,  644,  668,  659,    0,    0,  660,  661,  683,  680,
        0,    0,    0,    0,  681,  672,    0,    0,  674,    0,

      680,    0,  680,    0,  677,  678,    0,  686,    0,    0,
        0,    0,    0,  784,  751,  756,  758,  763,  768,  178,
      773,  173,  154,  778,  133,   85
    } ;

static const flex_int16_t yy_def[327] =
    {   0,
      314,    1,  315,  315,  314,  314,  314,  314,  314,  314,
      314,  314,  316,  314,  314,  314,  314,  314,  314,  314,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  314,  318,  314,
      314,  314,  319,  314,  314,  320,  314,  321,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  314,  318,  318,  314,  314,  319,

      314,  320,  321,  314,  314,  321,  321,  321,  321,  321,
      321,  322,  321,  321,  321,  321,  314,  323,  314,  314,
      314,  314,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  324,  314,  321,  321,
      321,  321,  321,  325,  321,  321,  321,  321,  321,  321,
      321,  323,  314,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  324,  321,
      321,  171,  321,  323,  314,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  321,  314,  314,  314,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      314,  326,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      326,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,    0,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314
    } ;

static const flex_int16_t yy_nxt[868] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   14,
       15,   11,   14,   16,   17,   11,   18,   18,   18,   18,
       14,   14,   19,   20,   11,   11,   21,   22,   23,   24,
       25,   26,   22,   27,   22,   22,   22,   28,   29,   30,
       31,   32,   22,   33,   34,   35,   36,   37,   22,   22,
       22,   11,   11,   11,   38,   21,   22,   23,   24,   25,
       26,   22,   27,   22,   22,   28,   29,   30,   31,   32,
       22,   33,   34,   35,   36,   37,   22,   22,   22,   14,
       39,   14,   11,   43,   49,   97,   53,   50,  291,   70,
       73,   79,   44,   81,   82,   45,   45,   45,   54,   54,

       54,   54,   55,   80,   56,   56,   56,   56,   58,   59,
       71,   83,   46,   60,   61,   84,   62,   70,   63,   73,
       79,   85,   81,   82,   72,   64,   65,   66,   67,   88,
       86,   80,   93,   74,   94,  104,  103,   75,  105,   71,
       83,   46,   76,   77,   84,  123,   78,   87,   89,   85,
       98,  104,   72,   91,   50,  130,   90,  172,   88,   86,
       93,   92,   74,   94,   55,   75,   45,   45,   45,  104,
       76,   77,   50,  123,   78,   87,   48,   89,  117,  117,
      117,  102,   91,   68,  130,   90,   54,   54,   54,   54,
       92,  106,   55,  127,  135,  118,  107,   53,  128,   55,

      119,   56,   56,   56,   56,  108,  109,  108,  131,   54,
       54,   54,   54,  101,  129,  107,  110,  124,  133,  125,
      111,  127,  112,  135,  118,  132,  136,  128,  113,  119,
      137,  122,  114,  126,  115,  134,  116,  131,  139,  142,
      157,  138,  129,  143,  107,  110,  124,  133,  125,  111,
      144,  112,  140,  132,  145,  136,  113,  146,  151,  137,
      114,  126,  115,  134,  116,  147,  139,  142,  141,  138,
      152,  148,  143,  149,  314,  153,  154,  155,  150,  144,
      156,  140,  145,  121,  104,  146,  151,  105,  104,  104,
      104,  105,  105,  105,  147,  173,  141,  104,  152,  148,

      105,  174,  149,  153,  154,  158,  155,  150,  156,  169,
      169,  169,  104,  171,  171,  105,  104,  104,  104,  105,
      105,  105,  175,  173,  170,  170,  170,  117,  117,  117,
      174,  178,  182,  176,  120,  183,  101,  177,  179,  314,
      106,  119,   99,  184,  185,  159,  188,  180,  181,  186,
      187,  175,  189,  190,  160,  161,  160,  191,  192,  193,
      178,  182,  176,  183,  159,  162,  177,  179,  194,  163,
      119,  164,  184,  185,  188,  180,  181,  165,  186,  187,
      189,  166,  190,  167,  195,  168,  191,  192,  193,  196,
      197,  198,  199,  159,  162,  200,  201,  194,  163,  202,

      164,  203,  204,  205,  208,  165,  206,  207,   95,  166,
       57,  167,  195,  168,   52,  104,  214,  196,   50,  197,
      198,  199,   51,  200,   47,  201,   42,  202,  104,  203,
      204,   50,  205,  208,  206,  207,  104,  212,  212,   50,
      210,  210,  210,  104,  104,  214,   50,   50,  211,  211,
      211,  104,  104,  104,   50,   50,   50,  104,  104,  104,
       50,  105,  105,  215,  216,  217,  104,  218,  314,   50,
       41,  169,  169,  169,  104,  219,  222,  105,  220,  221,
      223,  157,  224,  225,  226,  227,  213,  213,  213,  213,
      228,  215,  216,  229,  217,  218,  213,  213,  213,  213,

      213,  213,   41,  230,  219,  222,  220,  221,  231,  223,
      224,  225,  226,  227,  232,  233,  314,  234,  228,  235,
      237,  229,  236,  238,  239,  213,  213,  213,  213,  213,
      213,  230,  240,  241,  242,  243,  231,  104,  314,  314,
      105,  214,  248,  232,  233,  234,  158,  249,  235,  237,
      236,  238,  314,  239,  104,  250,  251,   50,  253,  173,
      240,  241,  242,  314,  243,  314,  210,  210,  210,   50,
      214,  248,  254,  252,  314,  257,  249,  255,  244,  244,
      244,  244,  256,  250,  251,  258,  253,  173,  244,  244,
      244,  244,  244,  244,  245,  259,  260,  261,  262,  266,

      254,  246,  252,  246,  257,  255,  247,  247,  247,  247,
      256,  263,  264,  258,  265,  267,  270,  244,  244,  244,
      244,  244,  244,  268,  259,  260,  261,  262,  266,  269,
      104,  273,  274,   50,  245,  271,  271,  271,  275,  263,
      264,  276,  265,  277,  267,  270,  247,  247,  247,  247,
      278,  268,  272,  247,  247,  247,  247,  269,  279,  273,
      280,  274,  281,  314,  282,  283,  275,  284,  287,  276,
      285,  277,  286,  288,  289,  290,  292,  296,  278,  293,
      294,  272,  271,  271,  271,  295,  297,  279,  298,  280,
      299,  281,  282,  283,  300,  303,  284,  287,  285,  301,

      286,  288,  289,  290,  302,  292,  296,  293,  294,  304,
      305,  306,  313,  295,  297,  307,  298,  308,  299,  309,
      310,  311,  312,  300,  303,  314,  314,  301,  314,  314,
      314,  314,  302,  314,  314,  314,  314,  314,  304,  305,
      306,  313,  314,  307,  314,  308,  314,  309,  310,  311,
      312,   40,   40,   40,   40,   40,   48,  314,   48,   48,
       48,   69,   69,   96,  314,   96,   96,   96,  100,  100,
      100,  100,  100,  103,  314,  103,  103,  103,  209,  314,
      314,  209,  209,    5,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314
    } ;

static const flex_int16_t yy_chk[868] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   10,   13,   39,   17,   13,  326,   21,
       24,   26,   10,   27,   28,   10,   10,   10,   17,   17,

       17,   17,   18,   26,   18,   18,   18,   18,   20,   20,
       23,   29,   10,   20,   20,   30,   20,   21,   20,   24,
       26,   31,   27,   28,   23,   20,   20,   20,   20,   33,
       32,   26,   36,   25,   37,   48,  325,   25,   48,   23,
       29,   10,   25,   25,   30,   70,   25,   32,   34,   31,
       39,  103,   23,   35,  103,   74,   34,  323,   33,   32,
       36,   35,   25,   37,   45,   25,   45,   45,   45,  106,
       25,   25,  106,   70,   25,   32,  322,   34,   53,   53,
       53,  320,   35,   20,   74,   34,   54,   54,   54,   54,
       35,   49,  102,   72,   77,   53,   49,   55,   73,   56,

       54,   56,   56,   56,   56,   49,   49,   49,   75,   55,
       55,   55,   55,  100,   73,   49,   49,   71,   76,   71,
       49,   72,   49,   77,   53,   75,   78,   73,   49,   54,
       79,   64,   49,   71,   49,   76,   49,   75,   80,   82,
       96,   79,   73,   83,   49,   49,   71,   76,   71,   49,
       84,   49,   81,   75,   85,   78,   49,   86,   89,   79,
       49,   71,   49,   76,   49,   87,   80,   82,   81,   79,
       90,   87,   83,   88,   97,   91,   92,   93,   88,   84,
       94,   81,   85,   62,  107,   86,   89,  107,  110,  111,
      113,  110,  111,  113,   87,  119,   81,  108,   90,   87,

      108,  123,   88,   91,   92,   96,   93,   88,   94,  108,
      108,  108,  109,  112,  112,  109,  114,  115,  116,  114,
      115,  116,  124,  119,  109,  109,  109,  117,  117,  117,
      123,  126,  128,  125,   60,  129,   43,  125,  127,   97,
      104,  117,   41,  130,  131,  104,  134,  127,  127,  132,
      133,  124,  135,  136,  104,  104,  104,  137,  139,  140,
      126,  128,  125,  129,  104,  104,  125,  127,  141,  104,
      117,  104,  130,  131,  134,  127,  127,  104,  132,  133,
      135,  104,  136,  104,  142,  104,  137,  139,  140,  143,
      144,  145,  146,  104,  104,  147,  148,  141,  104,  149,

      104,  151,  152,  153,  156,  104,  154,  155,   38,  104,
       19,  104,  142,  104,   16,  159,  172,  143,  159,  144,
      145,  146,   15,  147,   12,  148,    9,  149,  160,  151,
      152,  160,  153,  156,  154,  155,  161,  164,  164,  161,
      160,  160,  160,  162,  163,  172,  162,  163,  161,  161,
      161,  165,  166,  167,  165,  166,  167,  168,  169,  170,
      168,  169,  170,  173,  174,  175,  210,  177,    5,  210,
        4,  170,  170,  170,  171,  178,  181,  171,  179,  180,
      182,  209,  183,  184,  185,  186,  171,  171,  171,  171,
      187,  173,  174,  188,  175,  177,  171,  171,  171,  171,

      171,  171,    3,  189,  178,  181,  179,  180,  190,  182,
      183,  184,  185,  186,  191,  192,    0,  193,  187,  195,
      200,  188,  196,  201,  203,  171,  171,  171,  171,  171,
      171,  189,  205,  206,  207,  208,  190,  213,    0,    0,
      213,  214,  217,  191,  192,  193,  209,  218,  195,  200,
      196,  201,    0,  203,  211,  219,  220,  211,  222,  214,
      205,  206,  207,    0,  208,    0,  211,  211,  211,  212,
      214,  217,  223,  221,    0,  226,  218,  224,  212,  212,
      212,  212,  225,  219,  220,  227,  222,  214,  212,  212,
      212,  212,  212,  212,  215,  228,  229,  230,  231,  237,

      223,  215,  221,  215,  226,  224,  215,  215,  215,  215,
      225,  232,  233,  227,  236,  238,  243,  212,  212,  212,
      212,  212,  212,  239,  228,  229,  230,  231,  237,  240,
      244,  248,  250,  244,  246,  245,  245,  245,  251,  232,
      233,  252,  236,  253,  238,  243,  246,  246,  246,  246,
      254,  239,  245,  247,  247,  247,  247,  240,  255,  248,
      256,  250,  257,    0,  260,  261,  251,  262,  265,  252,
      263,  253,  264,  266,  267,  270,  273,  277,  254,  274,
      275,  245,  271,  271,  271,  276,  279,  255,  281,  256,
      282,  257,  260,  261,  283,  288,  262,  265,  263,  284,

      264,  266,  267,  270,  287,  273,  277,  274,  275,  289,
      290,  295,  308,  276,  279,  296,  281,  299,  282,  301,
      303,  305,  306,  283,  288,    0,    0,  284,    0,    0,
        0,    0,  287,    0,    0,    0,    0,    0,  289,  290,
      295,  308,    0,  296,    0,  299,    0,  301,  303,  305,
      306,  315,  315,  315,  315,  315,  316,    0,  316,  316,
      316,  317,  317,  318,    0,  318,  318,  318,  319,  319,
      319,  319,  319,  321,    0,  321,  321,  321,  324,    0,
        0,  324,  324,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[80] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mini.l"
#line 2 "mini.l"
  #include <stdio.h>
  #include "mini.tab.h"
#line 772 "lex.yy.c"

#line 774 "lex.yy.c"

#define INITIAL 0
#define COMENTARIO 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 25 "mini.l"

#line 994 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 315 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 784 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "mini.l"
{printf("linea %d, - - - - -  Tamaño: %s\n", yylineno, yytext); return(TAMANO);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ARRAY);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CABECERA);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CADA);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CADENA);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CARACTER);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CONJUNTO);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CONSTANTES);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(CONTINUAR);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(DE);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(DEFECTO);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(DEVOLVER);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(EJECUTA);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ENCAMBIO);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ENTERO);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ES);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ESCAPE);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ESTRUCTURA);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(ETIQUETA);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 46 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(EXCEPCION);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 47 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(FICHERO);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(FIN);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(FUNCION);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 50 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(HACER);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(HASH);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(LANZA);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(MIENTRAS);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(NADA);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(OTRA);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(PARA);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(PRINCIPIO);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 58 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(PROGRAMA);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(REAL);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 60 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(REF);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 61 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(SALTAR);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 62 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(SI);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 63 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(SINO);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 64 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(TIPOS);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 65 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(UNION);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 66 "mini.l"
{printf("linea %d, palabra reservada: %s\n", yylineno, yytext); return(VARIABLES);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "mini.l"
{printf("linea %d, identificador: %s\n", yylineno, yytext); return(IDENTIFICADOR);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "mini.l"
{printf("linea %d, decimal: %s\n", yylineno, yytext); return(CTC_ENTERA);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "mini.l"
{printf("linea %d, octal: %s\n", yylineno, yytext); return(CTC_ENTERA);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "mini.l"
{printf("linea %d, hexadecimal: %s\n", yylineno, yytext); return(CTC_ENTERA);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "mini.l"
{printf("linea %d, número real: %s\n", yylineno, yytext); return(CTC_REAL);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "mini.l"
{printf("linea %d, número real: %s\n", yylineno, yytext); return(CTC_REAL);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "mini.l"
{printf("linea %d, carácter: %s\n", yylineno, yytext); return(CTC_CARACTER);}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 75 "mini.l"
{printf("linea %d, cadena: %s\n", yylineno, yytext); return(CTC_CADENA);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "mini.l"
{printf("linea %d, ruta: %s\n", yylineno, yytext); return(RUTA);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "mini.l"
{printf("linea %d, delimitador: %s\n", yylineno, yytext); return(yytext[0]);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "mini.l"
{printf("linea %d, operador: %s\n", yylineno, yytext); return(yytext[0]);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 80 "mini.l"
{printf("linea %d, potencia: %s\n", yylineno, yytext); return(POTENCIA);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "mini.l"
{printf("linea %d, suma_asig: %s\n", yylineno, yytext); return(SUMA_ASIG);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 82 "mini.l"
{printf("linea %d, resta_asig: %s\n", yylineno, yytext); return(RESTA_ASIG);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "mini.l"
{printf("linea %d, multiplicar_asig: %s\n", yylineno, yytext); return(MULT_ASIG);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "mini.l"
{printf("linea %d, dividir_asig: %s\n", yylineno, yytext); return(DIV_ASIG);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 85 "mini.l"
{printf("linea %d, módulo_asig: %s\n", yylineno, yytext); return(MOD_ASIG);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 86 "mini.l"
{printf("linea %d, flechaIzq_asig: %s\n", yylineno, yytext); return(FI_ASIG);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 87 "mini.l"
{printf("linea %d, flechaDer_asig: %s\n", yylineno, yytext); return(FD_ASIG);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 88 "mini.l"
{printf("linea %d, AND_asig: %s\n", yylineno, yytext); return(AND_ASIG);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 89 "mini.l"
{printf("linea %d, XOR_asig: %s\n", yylineno, yytext); return(XOR_ASIG);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 90 "mini.l"
{printf("linea %d, OR_asig: %s\n", yylineno, yytext); return(OR_ASIG);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 91 "mini.l"
{printf("linea %d, potencia_asig: %s\n", yylineno, yytext); return(POT_ASIG);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 92 "mini.l"
{printf("linea %d, mayor_igual: %s\n", yylineno, yytext); return(GE);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 93 "mini.l"
{printf("linea %d, menor_igual: %s\n", yylineno, yytext); return(LE);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 94 "mini.l"
{printf("linea %d, igual: %s\n", yylineno, yytext); return(EQ);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 95 "mini.l"
{printf("linea %d, distinto: %s\n", yylineno, yytext); return(NEQ);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 96 "mini.l"
{printf("linea %d, AND: %s\n", yylineno, yytext); return(AND);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 97 "mini.l"
{printf("linea %d, OR: %s\n", yylineno, yytext); return(OR);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 98 "mini.l"
{printf("linea %d, flechaIzq: %s\n", yylineno, yytext); return(FLECHA_IZDA);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 99 "mini.l"
{printf("linea %d, flechaDer: %s\n", yylineno, yytext); return(FLECHA_DCHA);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 100 "mini.l"
{printf("linea %d, indirección: %s\n", yylineno, yytext); return(INDIRECCION);}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 103 "mini.l"
;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 104 "mini.l"
BEGIN(COMENTARIO);
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 105 "mini.l"
;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 106 "mini.l"
BEGIN(INITIAL);
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 108 "mini.l"
;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 110 "mini.l"
printf("linea %d, error\n", yylineno);
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 113 "mini.l"
ECHO;
	YY_BREAK
#line 1460 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMENTARIO):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 315 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 315 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 314);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 113 "mini.l"


